// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Weaver.Infrastructure;

#nullable disable

namespace Weaver.Infrastructure.Migrations
{
    [DbContext(typeof(WeaverDbContext))]
    [Migration("20250718172054_RefactorEverythingToTemplate")]
    partial class RefactorEverythingToTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceTemplateServiceTemplateOption", b =>
                {
                    b.Property<long>("ConfigId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceTemplateId")
                        .HasColumnType("bigint");

                    b.HasKey("ConfigId", "ServiceTemplateId");

                    b.HasIndex("ServiceTemplateId");

                    b.ToTable("ServiceTemplateServiceTemplateOption", (string)null);
                });

            modelBuilder.Entity("Weaver.Domain.Entities.ServiceTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("ServiceTemplates", (string)null);
                });

            modelBuilder.Entity("Weaver.Domain.Entities.ServiceTemplateOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("ServiceTemplateOptions", (string)null);
                });

            modelBuilder.Entity("ServiceTemplateServiceTemplateOption", b =>
                {
                    b.HasOne("Weaver.Domain.Entities.ServiceTemplateOption", null)
                        .WithMany()
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Weaver.Domain.Entities.ServiceTemplate", null)
                        .WithMany()
                        .HasForeignKey("ServiceTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
