// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Weaver.Infrastructure;

#nullable disable

namespace Weaver.Infrastructure.Migrations
{
    [DbContext(typeof(WeaverDbContext))]
    [Migration("20250727134556_ChangeServiceTemplateOptionConstraint")]
    partial class ChangeServiceTemplateOptionConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceTemplateServiceTemplateOption", b =>
                {
                    b.Property<long>("ConfigId")
                        .HasColumnType("bigint");

                    b.Property<long>("ServiceTemplateId")
                        .HasColumnType("bigint");

                    b.HasKey("ConfigId", "ServiceTemplateId");

                    b.HasIndex("ServiceTemplateId");

                    b.ToTable("ServiceTemplateServiceTemplateOption", (string)null);
                });

            modelBuilder.Entity("Weaver.Domain.Common.ServiceOptions.ServiceOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceOptions", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Weaver.Domain.Entities.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("Weaver.Domain.Entities.ServiceTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("ServiceTemplates", (string)null);
                });

            modelBuilder.Entity("Weaver.Domain.Entities.ServiceTemplateOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.HasIndex("Name", "Type")
                        .IsUnique();

                    b.ToTable("ServiceTemplateOptions", (string)null);
                });

            modelBuilder.Entity("Weaver.Domain.Common.ServiceOptions.ServiceOption<bool>", b =>
                {
                    b.HasBaseType("Weaver.Domain.Common.ServiceOptions.ServiceOption");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Weaver.Domain.Common.ServiceOptions.ServiceOption<double>", b =>
                {
                    b.HasBaseType("Weaver.Domain.Common.ServiceOptions.ServiceOption");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.ToTable("ServiceOptions", t =>
                        {
                            t.Property("Value")
                                .HasColumnName("ServiceOption_Value");
                        });

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Weaver.Domain.Common.ServiceOptions.ServiceOption<double[]>", b =>
                {
                    b.HasBaseType("Weaver.Domain.Common.ServiceOptions.ServiceOption");

                    b.PrimitiveCollection<double[]>("Value")
                        .HasColumnType("double precision[]");

                    b.ToTable("ServiceOptions", t =>
                        {
                            t.Property("Value")
                                .HasColumnName("ServiceOption_Value1");
                        });

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Weaver.Domain.Common.ServiceOptions.ServiceOption<string>", b =>
                {
                    b.HasBaseType("Weaver.Domain.Common.ServiceOptions.ServiceOption");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.ToTable("ServiceOptions", t =>
                        {
                            t.Property("Value")
                                .HasColumnName("ServiceOption_Value2");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Weaver.Domain.Common.ServiceOptions.ServiceOption<string[]>", b =>
                {
                    b.HasBaseType("Weaver.Domain.Common.ServiceOptions.ServiceOption");

                    b.PrimitiveCollection<string[]>("Value")
                        .HasColumnType("text[]");

                    b.ToTable("ServiceOptions", t =>
                        {
                            t.Property("Value")
                                .HasColumnName("ServiceOption_Value3");
                        });

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("ServiceTemplateServiceTemplateOption", b =>
                {
                    b.HasOne("Weaver.Domain.Entities.ServiceTemplateOption", null)
                        .WithMany()
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Weaver.Domain.Entities.ServiceTemplate", null)
                        .WithMany()
                        .HasForeignKey("ServiceTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Weaver.Domain.Common.ServiceOptions.ServiceOption", b =>
                {
                    b.HasOne("Weaver.Domain.Entities.Service", null)
                        .WithMany("Options")
                        .HasForeignKey("ServiceId");
                });

            modelBuilder.Entity("Weaver.Domain.Entities.Service", b =>
                {
                    b.HasOne("Weaver.Domain.Entities.ServiceTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Weaver.Domain.Entities.Service", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
