/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  useMutation,
  useQuery
} from 'react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  ComposeProjectDetailModel,
  ComposeProjectListItemModel,
  CreateProjectCommand
} from '../models';



type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export const getComposeProject = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ComposeProjectListItemModel[]>> => {
    
    
    return axios.get(
      `/ComposeProject`,options
    );
  }




export const getGetComposeProjectQueryKey = () => {
    return [
    `/ComposeProject`
    ] as const;
    }

    
export const getGetComposeProjectQueryOptions = <TData = Awaited<ReturnType<typeof getComposeProject>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getComposeProject>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetComposeProjectQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getComposeProject>>> = ({ signal }) => getComposeProject({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getComposeProject>>, TError, TData> & { queryKey: QueryKey }
}

export type GetComposeProjectQueryResult = NonNullable<Awaited<ReturnType<typeof getComposeProject>>>
export type GetComposeProjectQueryError = AxiosError<unknown>



export function useGetComposeProject<TData = Awaited<ReturnType<typeof getComposeProject>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getComposeProject>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetComposeProjectQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putComposeProject = (
    createProjectCommand: CreateProjectCommand, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ComposeProjectDetailModel>> => {
    
    
    return axios.put(
      `/ComposeProject`,
      createProjectCommand,options
    );
  }



export const getPutComposeProjectMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putComposeProject>>, TError,{data: CreateProjectCommand}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putComposeProject>>, TError,{data: CreateProjectCommand}, TContext> => {

const mutationKey = ['putComposeProject'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putComposeProject>>, {data: CreateProjectCommand}> = (props) => {
          const {data} = props ?? {};

          return  putComposeProject(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutComposeProjectMutationResult = NonNullable<Awaited<ReturnType<typeof putComposeProject>>>
    export type PutComposeProjectMutationBody = CreateProjectCommand
    export type PutComposeProjectMutationError = AxiosError<unknown>

    export const usePutComposeProject = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putComposeProject>>, TError,{data: CreateProjectCommand}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putComposeProject>>,
        TError,
        {data: CreateProjectCommand},
        TContext
      > => {

      const mutationOptions = getPutComposeProjectMutationOptions(options);

      return useMutation(mutationOptions);
    }
    