/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  useMutation,
  useQuery
} from 'react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  ProblemDetails,
  PutServiceTemplateParams,
  PutServiceTemplateWithReferencesParams,
  ServiceTemplateDetailModel,
  ServiceTemplateListItemModel,
  ServiceTemplateOption
} from '../models';



type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export const putServiceTemplateWithReferences = (
    putServiceTemplateWithReferencesBody: string[],
    params?: PutServiceTemplateWithReferencesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.put(
      `/ServiceTemplate/with-references`,
      putServiceTemplateWithReferencesBody,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPutServiceTemplateWithReferencesMutationOptions = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putServiceTemplateWithReferences>>, TError,{data: string[];params?: PutServiceTemplateWithReferencesParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putServiceTemplateWithReferences>>, TError,{data: string[];params?: PutServiceTemplateWithReferencesParams}, TContext> => {

const mutationKey = ['putServiceTemplateWithReferences'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putServiceTemplateWithReferences>>, {data: string[];params?: PutServiceTemplateWithReferencesParams}> = (props) => {
          const {data,params} = props ?? {};

          return  putServiceTemplateWithReferences(data,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutServiceTemplateWithReferencesMutationResult = NonNullable<Awaited<ReturnType<typeof putServiceTemplateWithReferences>>>
    export type PutServiceTemplateWithReferencesMutationBody = string[]
    export type PutServiceTemplateWithReferencesMutationError = AxiosError<ProblemDetails>

    export const usePutServiceTemplateWithReferences = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putServiceTemplateWithReferences>>, TError,{data: string[];params?: PutServiceTemplateWithReferencesParams}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putServiceTemplateWithReferences>>,
        TError,
        {data: string[];params?: PutServiceTemplateWithReferencesParams},
        TContext
      > => {

      const mutationOptions = getPutServiceTemplateWithReferencesMutationOptions(options);

      return useMutation(mutationOptions );
    }
    export const putServiceTemplate = (
    serviceTemplateOption: ServiceTemplateOption[],
    params?: PutServiceTemplateParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.put(
      `/ServiceTemplate`,
      serviceTemplateOption,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPutServiceTemplateMutationOptions = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putServiceTemplate>>, TError,{data: ServiceTemplateOption[];params?: PutServiceTemplateParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putServiceTemplate>>, TError,{data: ServiceTemplateOption[];params?: PutServiceTemplateParams}, TContext> => {

const mutationKey = ['putServiceTemplate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putServiceTemplate>>, {data: ServiceTemplateOption[];params?: PutServiceTemplateParams}> = (props) => {
          const {data,params} = props ?? {};

          return  putServiceTemplate(data,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutServiceTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof putServiceTemplate>>>
    export type PutServiceTemplateMutationBody = ServiceTemplateOption[]
    export type PutServiceTemplateMutationError = AxiosError<ProblemDetails>

    export const usePutServiceTemplate = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putServiceTemplate>>, TError,{data: ServiceTemplateOption[];params?: PutServiceTemplateParams}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putServiceTemplate>>,
        TError,
        {data: ServiceTemplateOption[];params?: PutServiceTemplateParams},
        TContext
      > => {

      const mutationOptions = getPutServiceTemplateMutationOptions(options);

      return useMutation(mutationOptions );
    }
    export const getServiceTemplate = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ServiceTemplateListItemModel[]>> => {
    
    
    return axios.get(
      `/ServiceTemplate`,options
    );
  }


export const getGetServiceTemplateQueryKey = () => {
    return [`/ServiceTemplate`] as const;
    }

    
export const getGetServiceTemplateQueryOptions = <TData = Awaited<ReturnType<typeof getServiceTemplate>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceTemplate>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceTemplateQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceTemplate>>> = ({ signal }) => getServiceTemplate({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceTemplate>>, TError, TData> & { queryKey: QueryKey }
}

export type GetServiceTemplateQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceTemplate>>>
export type GetServiceTemplateQueryError = AxiosError<unknown>



export function useGetServiceTemplate<TData = Awaited<ReturnType<typeof getServiceTemplate>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceTemplate>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetServiceTemplateQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getServiceTemplateUuid = (
    uuid: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ServiceTemplateDetailModel>> => {
    
    
    return axios.get(
      `/ServiceTemplate/${uuid}`,options
    );
  }


export const getGetServiceTemplateUuidQueryKey = (uuid: string,) => {
    return [`/ServiceTemplate/${uuid}`] as const;
    }

    
export const getGetServiceTemplateUuidQueryOptions = <TData = Awaited<ReturnType<typeof getServiceTemplateUuid>>, TError = AxiosError<ProblemDetails>>(uuid: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceTemplateUuid>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceTemplateUuidQueryKey(uuid);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceTemplateUuid>>> = ({ signal }) => getServiceTemplateUuid(uuid, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(uuid), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceTemplateUuid>>, TError, TData> & { queryKey: QueryKey }
}

export type GetServiceTemplateUuidQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceTemplateUuid>>>
export type GetServiceTemplateUuidQueryError = AxiosError<ProblemDetails>



export function useGetServiceTemplateUuid<TData = Awaited<ReturnType<typeof getServiceTemplateUuid>>, TError = AxiosError<ProblemDetails>>(
 uuid: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceTemplateUuid>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetServiceTemplateUuidQueryOptions(uuid,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



