/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  useMutation,
  useQuery
} from 'react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  ProblemDetails,
  PutServiceTemplateOptionParams,
  ServiceTemplateOptionModel
} from '../models';



type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export const putServiceTemplateOption = (
    params?: PutServiceTemplateOptionParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.put(
      `/ServiceTemplateOption`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPutServiceTemplateOptionMutationOptions = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putServiceTemplateOption>>, TError,{params?: PutServiceTemplateOptionParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putServiceTemplateOption>>, TError,{params?: PutServiceTemplateOptionParams}, TContext> => {

const mutationKey = ['putServiceTemplateOption'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putServiceTemplateOption>>, {params?: PutServiceTemplateOptionParams}> = (props) => {
          const {params} = props ?? {};

          return  putServiceTemplateOption(params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutServiceTemplateOptionMutationResult = NonNullable<Awaited<ReturnType<typeof putServiceTemplateOption>>>
    
    export type PutServiceTemplateOptionMutationError = AxiosError<ProblemDetails>

    export const usePutServiceTemplateOption = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putServiceTemplateOption>>, TError,{params?: PutServiceTemplateOptionParams}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putServiceTemplateOption>>,
        TError,
        {params?: PutServiceTemplateOptionParams},
        TContext
      > => {

      const mutationOptions = getPutServiceTemplateOptionMutationOptions(options);

      return useMutation(mutationOptions );
    }
    export const getServiceTemplateOption = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ServiceTemplateOptionModel[]>> => {
    
    
    return axios.get(
      `/ServiceTemplateOption`,options
    );
  }


export const getGetServiceTemplateOptionQueryKey = () => {
    return [`/ServiceTemplateOption`] as const;
    }

    
export const getGetServiceTemplateOptionQueryOptions = <TData = Awaited<ReturnType<typeof getServiceTemplateOption>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceTemplateOption>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceTemplateOptionQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceTemplateOption>>> = ({ signal }) => getServiceTemplateOption({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceTemplateOption>>, TError, TData> & { queryKey: QueryKey }
}

export type GetServiceTemplateOptionQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceTemplateOption>>>
export type GetServiceTemplateOptionQueryError = AxiosError<unknown>



export function useGetServiceTemplateOption<TData = Awaited<ReturnType<typeof getServiceTemplateOption>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceTemplateOption>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetServiceTemplateOptionQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getServiceTemplateOptionUuid = (
    uuid: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ServiceTemplateOptionModel>> => {
    
    
    return axios.get(
      `/ServiceTemplateOption/${uuid}`,options
    );
  }


export const getGetServiceTemplateOptionUuidQueryKey = (uuid: string,) => {
    return [`/ServiceTemplateOption/${uuid}`] as const;
    }

    
export const getGetServiceTemplateOptionUuidQueryOptions = <TData = Awaited<ReturnType<typeof getServiceTemplateOptionUuid>>, TError = AxiosError<ProblemDetails>>(uuid: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceTemplateOptionUuid>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceTemplateOptionUuidQueryKey(uuid);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceTemplateOptionUuid>>> = ({ signal }) => getServiceTemplateOptionUuid(uuid, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(uuid), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceTemplateOptionUuid>>, TError, TData> & { queryKey: QueryKey }
}

export type GetServiceTemplateOptionUuidQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceTemplateOptionUuid>>>
export type GetServiceTemplateOptionUuidQueryError = AxiosError<ProblemDetails>



export function useGetServiceTemplateOptionUuid<TData = Awaited<ReturnType<typeof getServiceTemplateOptionUuid>>, TError = AxiosError<ProblemDetails>>(
 uuid: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceTemplateOptionUuid>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetServiceTemplateOptionUuidQueryOptions(uuid,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



