/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  useMutation,
  useQuery
} from 'react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  PatchServiceParams,
  ProblemDetails,
  PutServiceParams,
  ServiceDetailModel,
  ServiceListItemModel,
  ServiceOptionModel
} from '../models';



type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export const putService = (
    serviceOptionModel: ServiceOptionModel[],
    params?: PutServiceParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.put(
      `/Service`,
      serviceOptionModel,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPutServiceMutationOptions = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putService>>, TError,{data: ServiceOptionModel[];params?: PutServiceParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putService>>, TError,{data: ServiceOptionModel[];params?: PutServiceParams}, TContext> => {

const mutationKey = ['putService'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putService>>, {data: ServiceOptionModel[];params?: PutServiceParams}> = (props) => {
          const {data,params} = props ?? {};

          return  putService(data,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutServiceMutationResult = NonNullable<Awaited<ReturnType<typeof putService>>>
    export type PutServiceMutationBody = ServiceOptionModel[]
    export type PutServiceMutationError = AxiosError<ProblemDetails>

    export const usePutService = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putService>>, TError,{data: ServiceOptionModel[];params?: PutServiceParams}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putService>>,
        TError,
        {data: ServiceOptionModel[];params?: PutServiceParams},
        TContext
      > => {

      const mutationOptions = getPutServiceMutationOptions(options);

      return useMutation(mutationOptions );
    }
    export const patchService = (
    serviceOptionModel: ServiceOptionModel[],
    params?: PatchServiceParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.patch(
      `/Service`,
      serviceOptionModel,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPatchServiceMutationOptions = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchService>>, TError,{data: ServiceOptionModel[];params?: PatchServiceParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof patchService>>, TError,{data: ServiceOptionModel[];params?: PatchServiceParams}, TContext> => {

const mutationKey = ['patchService'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchService>>, {data: ServiceOptionModel[];params?: PatchServiceParams}> = (props) => {
          const {data,params} = props ?? {};

          return  patchService(data,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchServiceMutationResult = NonNullable<Awaited<ReturnType<typeof patchService>>>
    export type PatchServiceMutationBody = ServiceOptionModel[]
    export type PatchServiceMutationError = AxiosError<ProblemDetails>

    export const usePatchService = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchService>>, TError,{data: ServiceOptionModel[];params?: PatchServiceParams}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchService>>,
        TError,
        {data: ServiceOptionModel[];params?: PatchServiceParams},
        TContext
      > => {

      const mutationOptions = getPatchServiceMutationOptions(options);

      return useMutation(mutationOptions );
    }
    export const getService = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ServiceListItemModel[]>> => {
    
    
    return axios.get(
      `/Service`,options
    );
  }


export const getGetServiceQueryKey = () => {
    return [`/Service`] as const;
    }

    
export const getGetServiceQueryOptions = <TData = Awaited<ReturnType<typeof getService>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getService>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getService>>> = ({ signal }) => getService({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getService>>, TError, TData> & { queryKey: QueryKey }
}

export type GetServiceQueryResult = NonNullable<Awaited<ReturnType<typeof getService>>>
export type GetServiceQueryError = AxiosError<unknown>



export function useGetService<TData = Awaited<ReturnType<typeof getService>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getService>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetServiceQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getServiceUuid = (
    uuid: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ServiceDetailModel>> => {
    
    
    return axios.get(
      `/Service/${uuid}`,options
    );
  }


export const getGetServiceUuidQueryKey = (uuid: string,) => {
    return [`/Service/${uuid}`] as const;
    }

    
export const getGetServiceUuidQueryOptions = <TData = Awaited<ReturnType<typeof getServiceUuid>>, TError = AxiosError<ProblemDetails>>(uuid: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceUuid>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceUuidQueryKey(uuid);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceUuid>>> = ({ signal }) => getServiceUuid(uuid, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(uuid), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceUuid>>, TError, TData> & { queryKey: QueryKey }
}

export type GetServiceUuidQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceUuid>>>
export type GetServiceUuidQueryError = AxiosError<ProblemDetails>



export function useGetServiceUuid<TData = Awaited<ReturnType<typeof getServiceUuid>>, TError = AxiosError<ProblemDetails>>(
 uuid: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceUuid>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetServiceUuidQueryOptions(uuid,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



