/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  useMutation,
  useQuery
} from 'react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  ProblemDetails,
  PutServiceOptionParams,
  PutServiceParams,
  ServiceDetailModel,
  ServiceListItemModel,
  ServiceOptionModel
} from '../models';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export const putService = (
    putServiceBody: string[],
    params?: PutServiceParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.put(
      `/Service`,
      putServiceBody,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPutServiceMutationOptions = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putService>>, TError,{data: string[];params?: PutServiceParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putService>>, TError,{data: string[];params?: PutServiceParams}, TContext> => {

const mutationKey = ['putService'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putService>>, {data: string[];params?: PutServiceParams}> = (props) => {
          const {data,params} = props ?? {};

          return  putService(data,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutServiceMutationResult = NonNullable<Awaited<ReturnType<typeof putService>>>
    export type PutServiceMutationBody = string[]
    export type PutServiceMutationError = AxiosError<ProblemDetails>

    export const usePutService = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putService>>, TError,{data: string[];params?: PutServiceParams}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putService>>,
        TError,
        {data: string[];params?: PutServiceParams},
        TContext
      > => {

      const mutationOptions = getPutServiceMutationOptions(options);

      return useMutation(mutationOptions );
    }
    
export const getService = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ServiceListItemModel[]>> => {
    
    
    return axios.get(
      `/Service`,options
    );
  }


export const getGetServiceQueryKey = () => {
    return [`/Service`] as const;
    }

    
export const getGetServiceQueryOptions = <TData = Awaited<ReturnType<typeof getService>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getService>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getService>>> = ({ signal }) => getService({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getService>>, TError, TData> & { queryKey: QueryKey }
}

export type GetServiceQueryResult = NonNullable<Awaited<ReturnType<typeof getService>>>
export type GetServiceQueryError = AxiosError<unknown>



export function useGetService<TData = Awaited<ReturnType<typeof getService>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getService>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetServiceQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getServiceUuid = (
    uuid: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ServiceDetailModel>> => {
    
    
    return axios.get(
      `/Service/${uuid}`,options
    );
  }


export const getGetServiceUuidQueryKey = (uuid: string,) => {
    return [`/Service/${uuid}`] as const;
    }

    
export const getGetServiceUuidQueryOptions = <TData = Awaited<ReturnType<typeof getServiceUuid>>, TError = AxiosError<ProblemDetails>>(uuid: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceUuid>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceUuidQueryKey(uuid);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceUuid>>> = ({ signal }) => getServiceUuid(uuid, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(uuid), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceUuid>>, TError, TData> & { queryKey: QueryKey }
}

export type GetServiceUuidQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceUuid>>>
export type GetServiceUuidQueryError = AxiosError<ProblemDetails>



export function useGetServiceUuid<TData = Awaited<ReturnType<typeof getServiceUuid>>, TError = AxiosError<ProblemDetails>>(
 uuid: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceUuid>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetServiceUuidQueryOptions(uuid,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putServiceOption = (
    params?: PutServiceOptionParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.put(
      `/ServiceOption`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPutServiceOptionMutationOptions = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putServiceOption>>, TError,{params?: PutServiceOptionParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putServiceOption>>, TError,{params?: PutServiceOptionParams}, TContext> => {

const mutationKey = ['putServiceOption'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putServiceOption>>, {params?: PutServiceOptionParams}> = (props) => {
          const {params} = props ?? {};

          return  putServiceOption(params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutServiceOptionMutationResult = NonNullable<Awaited<ReturnType<typeof putServiceOption>>>
    
    export type PutServiceOptionMutationError = AxiosError<ProblemDetails>

    export const usePutServiceOption = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putServiceOption>>, TError,{params?: PutServiceOptionParams}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putServiceOption>>,
        TError,
        {params?: PutServiceOptionParams},
        TContext
      > => {

      const mutationOptions = getPutServiceOptionMutationOptions(options);

      return useMutation(mutationOptions );
    }
    
export const getServiceOption = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ServiceOptionModel[]>> => {
    
    
    return axios.get(
      `/ServiceOption`,options
    );
  }


export const getGetServiceOptionQueryKey = () => {
    return [`/ServiceOption`] as const;
    }

    
export const getGetServiceOptionQueryOptions = <TData = Awaited<ReturnType<typeof getServiceOption>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceOption>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceOptionQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceOption>>> = ({ signal }) => getServiceOption({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceOption>>, TError, TData> & { queryKey: QueryKey }
}

export type GetServiceOptionQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceOption>>>
export type GetServiceOptionQueryError = AxiosError<unknown>



export function useGetServiceOption<TData = Awaited<ReturnType<typeof getServiceOption>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceOption>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetServiceOptionQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getServiceOptionUuid = (
    uuid: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ServiceOptionModel>> => {
    
    
    return axios.get(
      `/ServiceOption/${uuid}`,options
    );
  }


export const getGetServiceOptionUuidQueryKey = (uuid: string,) => {
    return [`/ServiceOption/${uuid}`] as const;
    }

    
export const getGetServiceOptionUuidQueryOptions = <TData = Awaited<ReturnType<typeof getServiceOptionUuid>>, TError = AxiosError<ProblemDetails>>(uuid: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceOptionUuid>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceOptionUuidQueryKey(uuid);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceOptionUuid>>> = ({ signal }) => getServiceOptionUuid(uuid, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(uuid), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceOptionUuid>>, TError, TData> & { queryKey: QueryKey }
}

export type GetServiceOptionUuidQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceOptionUuid>>>
export type GetServiceOptionUuidQueryError = AxiosError<ProblemDetails>



export function useGetServiceOptionUuid<TData = Awaited<ReturnType<typeof getServiceOptionUuid>>, TError = AxiosError<ProblemDetails>>(
 uuid: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceOptionUuid>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetServiceOptionUuidQueryOptions(uuid,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getTest = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ServiceOptionModel[]>> => {
    
    
    return axios.get(
      `/Test`,options
    );
  }


export const getGetTestQueryKey = () => {
    return [`/Test`] as const;
    }

    
export const getGetTestQueryOptions = <TData = Awaited<ReturnType<typeof getTest>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTest>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTestQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTest>>> = ({ signal }) => getTest({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTest>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTestQueryResult = NonNullable<Awaited<ReturnType<typeof getTest>>>
export type GetTestQueryError = AxiosError<unknown>



export function useGetTest<TData = Awaited<ReturnType<typeof getTest>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTest>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTestQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




