/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { BindOptionsPropagation } from './bind-options-propagation';

export interface BindOptions {
  Propagation?: BindOptionsPropagation;
  NonRecursive?: boolean;
  CreateMountpoint?: boolean;
  ReadOnlyNonRecursive?: boolean;
  ReadOnlyForceRecursive?: boolean;
}
