/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ContainerListItemModel } from './container-list-item-model';

export interface ComposeModel {
  id?: string;
  name?: string;
  containers?: ContainerListItemModel[];
}
