/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Health } from './health';
import type { Status } from './status';
import type { PortMapping } from './port-mapping';

export interface ComposeListItemModel {
  id: string;
  name: string;
  health: Health;
  status: Status;
  containerNames: string[];
  ports: PortMapping[];
}
