/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PortSummary } from './port-summary';
import type { HealthSummary } from './health-summary';
import type { NetworkSettingsSummary } from './network-settings-summary';
import type { MountPoint } from './mount-point';

export interface ContainerDetailModel {
  id?: string;
  names?: string[];
  image?: string;
  imageId?: string;
  created?: string;
  ports?: PortSummary[];
  state?: string;
  status?: string;
  health?: HealthSummary;
  networkSettingsSummary?: NetworkSettingsSummary;
  mounts?: MountPoint[];
  logs?: string;
}
