/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PortSummary } from './port-summary';
import type { Status } from './status';
import type { Health } from './health';
import type { HealthSummary } from './health-summary';
import type { NetworkSettingsSummary } from './network-settings-summary';
import type { MountPoint } from './mount-point';
import type { EnvironmentVariable } from './environment-variable';

export interface ContainerDetailModel {
  id: string;
  names: string[];
  image: string;
  imageId: string;
  created: string;
  ports: PortSummary[];
  status: Status;
  health: Health;
  healthSummary: HealthSummary;
  networkSettingsSummary: NetworkSettingsSummary;
  mounts: MountPoint[];
  environmentVariables: EnvironmentVariable[];
  log: string;
}
