/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Status } from './status';
import type { Health } from './health';
import type { NetworkModel } from './network-model';
import type { ContainerListItemModelComposeName } from './container-list-item-model-compose-name';

export interface ContainerListItemModel {
  id: string;
  name: string;
  image: string;
  status: Status;
  created: string;
  health: Health;
  dependsOn: string[];
  networks: NetworkModel[];
  composeName?: ContainerListItemModelComposeName;
}
