/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreateContainerParametersName } from './create-container-parameters-name';
import type { CreateContainerParametersPlatform } from './create-container-parameters-platform';
import type { CreateContainerParametersHostname } from './create-container-parameters-hostname';
import type { CreateContainerParametersDomainname } from './create-container-parameters-domainname';
import type { CreateContainerParametersUser } from './create-container-parameters-user';
import type { CreateContainerParametersExposedPorts } from './create-container-parameters-exposed-ports';
import type { CreateContainerParametersEnv } from './create-container-parameters-env';
import type { CreateContainerParametersCmd } from './create-container-parameters-cmd';
import type { HealthcheckConfig } from './healthcheck-config';
import type { CreateContainerParametersImage } from './create-container-parameters-image';
import type { CreateContainerParametersVolumes } from './create-container-parameters-volumes';
import type { CreateContainerParametersWorkingDir } from './create-container-parameters-working-dir';
import type { CreateContainerParametersEntrypoint } from './create-container-parameters-entrypoint';
import type { CreateContainerParametersOnBuild } from './create-container-parameters-on-build';
import type { CreateContainerParametersLabels } from './create-container-parameters-labels';
import type { CreateContainerParametersStopSignal } from './create-container-parameters-stop-signal';
import type { CreateContainerParametersShell } from './create-container-parameters-shell';
import type { HostConfig } from './host-config';
import type { NetworkingConfig } from './networking-config';

export interface CreateContainerParameters {
  name?: CreateContainerParametersName;
  platform?: CreateContainerParametersPlatform;
  Hostname?: CreateContainerParametersHostname;
  Domainname?: CreateContainerParametersDomainname;
  User?: CreateContainerParametersUser;
  AttachStdin?: boolean;
  AttachStdout?: boolean;
  AttachStderr?: boolean;
  ExposedPorts?: CreateContainerParametersExposedPorts;
  Tty?: boolean;
  OpenStdin?: boolean;
  StdinOnce?: boolean;
  Env?: CreateContainerParametersEnv;
  Cmd?: CreateContainerParametersCmd;
  Healthcheck?: HealthcheckConfig;
  ArgsEscaped?: boolean;
  Image?: CreateContainerParametersImage;
  Volumes?: CreateContainerParametersVolumes;
  WorkingDir?: CreateContainerParametersWorkingDir;
  Entrypoint?: CreateContainerParametersEntrypoint;
  NetworkDisabled?: boolean;
  OnBuild?: CreateContainerParametersOnBuild;
  Labels?: CreateContainerParametersLabels;
  StopSignal?: CreateContainerParametersStopSignal;
  StopTimeout?: unknown;
  Shell?: CreateContainerParametersShell;
  HostConfig?: HostConfig;
  NetworkingConfig?: NetworkingConfig;
}
