/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DeviceMappingPathOnHost } from './device-mapping-path-on-host';
import type { DeviceMappingPathInContainer } from './device-mapping-path-in-container';
import type { DeviceMappingCgroupPermissions } from './device-mapping-cgroup-permissions';

export interface DeviceMapping {
  PathOnHost?: DeviceMappingPathOnHost;
  PathInContainer?: DeviceMappingPathInContainer;
  CgroupPermissions?: DeviceMappingCgroupPermissions;
}
