/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DeviceRequestDriver } from './device-request-driver';
import type { DeviceRequestCount } from './device-request-count';
import type { DeviceRequestDeviceIDs } from './device-request-device-i-ds';
import type { DeviceRequestCapabilities } from './device-request-capabilities';
import type { DeviceRequestOptions } from './device-request-options';

export interface DeviceRequest {
  Driver?: DeviceRequestDriver;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  Count?: DeviceRequestCount;
  DeviceIDs?: DeviceRequestDeviceIDs;
  Capabilities?: DeviceRequestCapabilities;
  Options?: DeviceRequestOptions;
}
