/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EndpointSettingsDriverOptsAnyOf } from './endpoint-settings-driver-opts-any-of';

export type EndpointSettingsDriverOpts = null | EndpointSettingsDriverOptsAnyOf;
