/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EndpointIPAMConfigIPv4Address } from './endpoint-ipam-config-i-pv4-address';
import type { EndpointIPAMConfigIPv6Address } from './endpoint-ipam-config-i-pv6-address';
import type { EndpointIPAMConfigLinkLocalIPs } from './endpoint-ipam-config-link-local-i-ps';

export interface EndpointIPAMConfig {
  IPv4Address?: EndpointIPAMConfigIPv4Address;
  IPv6Address?: EndpointIPAMConfigIPv6Address;
  LinkLocalIPs?: EndpointIPAMConfigLinkLocalIPs;
}
