/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EndpointIPAMConfig } from './endpoint-ipam-config';
import type { EndpointSettingsLinks } from './endpoint-settings-links';
import type { EndpointSettingsAliases } from './endpoint-settings-aliases';
import type { EndpointSettingsDriverOpts } from './endpoint-settings-driver-opts';
import type { EndpointSettingsGwPriority } from './endpoint-settings-gw-priority';
import type { EndpointSettingsNetworkID } from './endpoint-settings-network-i-d';
import type { EndpointSettingsEndpointID } from './endpoint-settings-endpoint-i-d';
import type { EndpointSettingsGateway } from './endpoint-settings-gateway';
import type { EndpointSettingsIPAddress } from './endpoint-settings-ip-address';
import type { EndpointSettingsMacAddress } from './endpoint-settings-mac-address';
import type { EndpointSettingsIPPrefixLen } from './endpoint-settings-ip-prefix-len';
import type { EndpointSettingsIPv6Gateway } from './endpoint-settings-i-pv6-gateway';
import type { EndpointSettingsGlobalIPv6Address } from './endpoint-settings-global-i-pv6-address';
import type { EndpointSettingsGlobalIPv6PrefixLen } from './endpoint-settings-global-i-pv6-prefix-len';
import type { EndpointSettingsDNSNames } from './endpoint-settings-dns-names';

export interface EndpointSettings {
  IPAMConfig?: EndpointIPAMConfig;
  Links?: EndpointSettingsLinks;
  Aliases?: EndpointSettingsAliases;
  DriverOpts?: EndpointSettingsDriverOpts;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  GwPriority?: EndpointSettingsGwPriority;
  NetworkID?: EndpointSettingsNetworkID;
  EndpointID?: EndpointSettingsEndpointID;
  Gateway?: EndpointSettingsGateway;
  IPAddress?: EndpointSettingsIPAddress;
  MacAddress?: EndpointSettingsMacAddress;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  IPPrefixLen?: EndpointSettingsIPPrefixLen;
  IPv6Gateway?: EndpointSettingsIPv6Gateway;
  GlobalIPv6Address?: EndpointSettingsGlobalIPv6Address;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  GlobalIPv6PrefixLen?: EndpointSettingsGlobalIPv6PrefixLen;
  DNSNames?: EndpointSettingsDNSNames;
}
