/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { HealthcheckConfigTest } from './healthcheck-config-test';
import type { HealthcheckConfigStartPeriod } from './healthcheck-config-start-period';
import type { HealthcheckConfigStartInterval } from './healthcheck-config-start-interval';
import type { HealthcheckConfigRetries } from './healthcheck-config-retries';

export interface HealthcheckConfig {
  Test?: HealthcheckConfigTest;
  Interval?: unknown;
  Timeout?: unknown;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  StartPeriod?: HealthcheckConfigStartPeriod;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  StartInterval?: HealthcheckConfigStartInterval;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  Retries?: HealthcheckConfigRetries;
}
