/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type HealthSummaryFailingStreak = number | string;
