/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export type Health = typeof Health[keyof typeof Health];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Health = {
  None: 'None',
  Unhealthy: 'Unhealthy',
  Starting: 'Starting',
  Healthy: 'Healthy',
} as const;
