/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { HealthSummaryStatus } from './health-summary-status';
import type { HealthSummaryFailingStreak } from './health-summary-failing-streak';

export interface HealthSummary {
  Status?: HealthSummaryStatus;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  FailingStreak?: HealthSummaryFailingStreak;
}
