/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { HostConfigPortBindingsAnyOf } from './host-config-port-bindings-any-of';

export type HostConfigPortBindings = null | HostConfigPortBindingsAnyOf;
