/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { HostConfigAnnotationsAnyOf } from './host-config-annotations-any-of';

export type HostConfigAnnotations = null | HostConfigAnnotationsAnyOf;
