/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { HostConfigTmpfsAnyOf } from './host-config-tmpfs-any-of';

export type HostConfigTmpfs = null | HostConfigTmpfsAnyOf;
