/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { HostConfigBinds } from './host-config-binds';
import type { HostConfigContainerIDFile } from './host-config-container-id-file';
import type { LogConfig } from './log-config';
import type { HostConfigNetworkMode } from './host-config-network-mode';
import type { HostConfigPortBindings } from './host-config-port-bindings';
import type { RestartPolicy } from './restart-policy';
import type { HostConfigVolumeDriver } from './host-config-volume-driver';
import type { HostConfigVolumesFrom } from './host-config-volumes-from';
import type { HostConfigConsoleSize } from './host-config-console-size';
import type { HostConfigAnnotations } from './host-config-annotations';
import type { HostConfigCapAdd } from './host-config-cap-add';
import type { HostConfigCapDrop } from './host-config-cap-drop';
import type { HostConfigCgroupnsMode } from './host-config-cgroupns-mode';
import type { HostConfigDns } from './host-config-dns';
import type { HostConfigDnsOptions } from './host-config-dns-options';
import type { HostConfigDnsSearch } from './host-config-dns-search';
import type { HostConfigExtraHosts } from './host-config-extra-hosts';
import type { HostConfigGroupAdd } from './host-config-group-add';
import type { HostConfigIpcMode } from './host-config-ipc-mode';
import type { HostConfigCgroup } from './host-config-cgroup';
import type { HostConfigLinks } from './host-config-links';
import type { HostConfigOomScoreAdj } from './host-config-oom-score-adj';
import type { HostConfigPidMode } from './host-config-pid-mode';
import type { HostConfigSecurityOpt } from './host-config-security-opt';
import type { HostConfigStorageOpt } from './host-config-storage-opt';
import type { HostConfigTmpfs } from './host-config-tmpfs';
import type { HostConfigUTSMode } from './host-config-uts-mode';
import type { HostConfigUsernsMode } from './host-config-userns-mode';
import type { HostConfigShmSize } from './host-config-shm-size';
import type { HostConfigSysctls } from './host-config-sysctls';
import type { HostConfigRuntime } from './host-config-runtime';
import type { HostConfigIsolation } from './host-config-isolation';
import type { HostConfigCpuShares } from './host-config-cpu-shares';
import type { HostConfigMemory } from './host-config-memory';
import type { HostConfigNanoCpus } from './host-config-nano-cpus';
import type { HostConfigCgroupParent } from './host-config-cgroup-parent';
import type { HostConfigBlkioWeight } from './host-config-blkio-weight';
import type { HostConfigBlkioWeightDevice } from './host-config-blkio-weight-device';
import type { HostConfigBlkioDeviceReadBps } from './host-config-blkio-device-read-bps';
import type { HostConfigBlkioDeviceWriteBps } from './host-config-blkio-device-write-bps';
import type { HostConfigBlkioDeviceReadIOps } from './host-config-blkio-device-read-i-ops';
import type { HostConfigBlkioDeviceWriteIOps } from './host-config-blkio-device-write-i-ops';
import type { HostConfigCpuPeriod } from './host-config-cpu-period';
import type { HostConfigCpuQuota } from './host-config-cpu-quota';
import type { HostConfigCpuRealtimePeriod } from './host-config-cpu-realtime-period';
import type { HostConfigCpuRealtimeRuntime } from './host-config-cpu-realtime-runtime';
import type { HostConfigCpusetCpus } from './host-config-cpuset-cpus';
import type { HostConfigCpusetMems } from './host-config-cpuset-mems';
import type { HostConfigDevices } from './host-config-devices';
import type { HostConfigDeviceCgroupRules } from './host-config-device-cgroup-rules';
import type { HostConfigDeviceRequests } from './host-config-device-requests';
import type { HostConfigMemoryReservation } from './host-config-memory-reservation';
import type { HostConfigMemorySwap } from './host-config-memory-swap';
import type { HostConfigMemorySwappiness } from './host-config-memory-swappiness';
import type { HostConfigOomKillDisable } from './host-config-oom-kill-disable';
import type { HostConfigPidsLimit } from './host-config-pids-limit';
import type { HostConfigUlimits } from './host-config-ulimits';
import type { HostConfigCpuCount } from './host-config-cpu-count';
import type { HostConfigCpuPercent } from './host-config-cpu-percent';
import type { HostConfigIOMaximumIOps } from './host-config-io-maximum-i-ops';
import type { HostConfigIOMaximumBandwidth } from './host-config-io-maximum-bandwidth';
import type { HostConfigMounts } from './host-config-mounts';
import type { HostConfigMaskedPaths } from './host-config-masked-paths';
import type { HostConfigReadonlyPaths } from './host-config-readonly-paths';
import type { HostConfigInit } from './host-config-init';

export interface HostConfig {
  Binds?: HostConfigBinds;
  ContainerIDFile?: HostConfigContainerIDFile;
  LogConfig?: LogConfig;
  NetworkMode?: HostConfigNetworkMode;
  PortBindings?: HostConfigPortBindings;
  RestartPolicy?: RestartPolicy;
  AutoRemove?: boolean;
  VolumeDriver?: HostConfigVolumeDriver;
  VolumesFrom?: HostConfigVolumesFrom;
  ConsoleSize?: HostConfigConsoleSize;
  Annotations?: HostConfigAnnotations;
  CapAdd?: HostConfigCapAdd;
  CapDrop?: HostConfigCapDrop;
  CgroupnsMode?: HostConfigCgroupnsMode;
  Dns?: HostConfigDns;
  DnsOptions?: HostConfigDnsOptions;
  DnsSearch?: HostConfigDnsSearch;
  ExtraHosts?: HostConfigExtraHosts;
  GroupAdd?: HostConfigGroupAdd;
  IpcMode?: HostConfigIpcMode;
  Cgroup?: HostConfigCgroup;
  Links?: HostConfigLinks;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  OomScoreAdj?: HostConfigOomScoreAdj;
  PidMode?: HostConfigPidMode;
  Privileged?: boolean;
  PublishAllPorts?: boolean;
  ReadonlyRootfs?: boolean;
  SecurityOpt?: HostConfigSecurityOpt;
  StorageOpt?: HostConfigStorageOpt;
  Tmpfs?: HostConfigTmpfs;
  UTSMode?: HostConfigUTSMode;
  UsernsMode?: HostConfigUsernsMode;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  ShmSize?: HostConfigShmSize;
  Sysctls?: HostConfigSysctls;
  Runtime?: HostConfigRuntime;
  Isolation?: HostConfigIsolation;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  CpuShares?: HostConfigCpuShares;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  Memory?: HostConfigMemory;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  NanoCpus?: HostConfigNanoCpus;
  CgroupParent?: HostConfigCgroupParent;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  BlkioWeight?: HostConfigBlkioWeight;
  BlkioWeightDevice?: HostConfigBlkioWeightDevice;
  BlkioDeviceReadBps?: HostConfigBlkioDeviceReadBps;
  BlkioDeviceWriteBps?: HostConfigBlkioDeviceWriteBps;
  BlkioDeviceReadIOps?: HostConfigBlkioDeviceReadIOps;
  BlkioDeviceWriteIOps?: HostConfigBlkioDeviceWriteIOps;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  CpuPeriod?: HostConfigCpuPeriod;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  CpuQuota?: HostConfigCpuQuota;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  CpuRealtimePeriod?: HostConfigCpuRealtimePeriod;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  CpuRealtimeRuntime?: HostConfigCpuRealtimeRuntime;
  CpusetCpus?: HostConfigCpusetCpus;
  CpusetMems?: HostConfigCpusetMems;
  Devices?: HostConfigDevices;
  DeviceCgroupRules?: HostConfigDeviceCgroupRules;
  DeviceRequests?: HostConfigDeviceRequests;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  MemoryReservation?: HostConfigMemoryReservation;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  MemorySwap?: HostConfigMemorySwap;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  MemorySwappiness?: HostConfigMemorySwappiness;
  OomKillDisable?: HostConfigOomKillDisable;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  PidsLimit?: HostConfigPidsLimit;
  Ulimits?: HostConfigUlimits;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  CpuCount?: HostConfigCpuCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  CpuPercent?: HostConfigCpuPercent;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  IOMaximumIOps?: HostConfigIOMaximumIOps;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  IOMaximumBandwidth?: HostConfigIOMaximumBandwidth;
  Mounts?: HostConfigMounts;
  MaskedPaths?: HostConfigMaskedPaths;
  ReadonlyPaths?: HostConfigReadonlyPaths;
  Init?: HostConfigInit;
}
