/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LogConfigType } from './log-config-type';
import type { LogConfigConfig } from './log-config-config';

export interface LogConfig {
  Type?: LogConfigType;
  Config?: LogConfigConfig;
}
