/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LogConfigConfigAnyOf } from './log-config-config-any-of';

export type LogConfigConfig = null | LogConfigConfigAnyOf;
