/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MountType } from './mount-type';
import type { MountSource } from './mount-source';
import type { MountTarget } from './mount-target';
import type { MountConsistency } from './mount-consistency';
import type { BindOptions } from './bind-options';
import type { VolumeOptions } from './volume-options';
import type { ImageOptions } from './image-options';
import type { TmpfsOptions } from './tmpfs-options';
import type { ClusterOptions } from './cluster-options';

export interface Mount {
  Type?: MountType;
  Source?: MountSource;
  Target?: MountTarget;
  ReadOnly?: boolean;
  Consistency?: MountConsistency;
  BindOptions?: BindOptions;
  VolumeOptions?: VolumeOptions;
  ImageOptions?: ImageOptions;
  TmpfsOptions?: TmpfsOptions;
  ClusterOptions?: ClusterOptions;
}
