/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MountPointType } from './mount-point-type';
import type { MountPointName } from './mount-point-name';
import type { MountPointSource } from './mount-point-source';
import type { MountPointDestination } from './mount-point-destination';
import type { MountPointDriver } from './mount-point-driver';
import type { MountPointMode } from './mount-point-mode';
import type { MountPointPropagation } from './mount-point-propagation';

export interface MountPoint {
  Type?: MountPointType;
  Name?: MountPointName;
  Source?: MountPointSource;
  Destination?: MountPointDestination;
  Driver?: MountPointDriver;
  Mode?: MountPointMode;
  RW?: boolean;
  Propagation?: MountPointPropagation;
}
