/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { NetworkingConfigEndpointsConfigAnyOf } from './networking-config-endpoints-config-any-of';

export type NetworkingConfigEndpointsConfig = null | NetworkingConfigEndpointsConfigAnyOf;
