/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PortSummaryIP } from './port-summary-i-p';
import type { PortSummaryPrivatePort } from './port-summary-private-port';
import type { PortSummaryPublicPort } from './port-summary-public-port';
import type { PortSummaryType } from './port-summary-type';

export interface PortSummary {
  IP?: PortSummaryIP;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  PrivatePort?: PortSummaryPrivatePort;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  PublicPort?: PortSummaryPublicPort;
  Type?: PortSummaryType;
}
