/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PortBindingHostIp } from './port-binding-host-ip';
import type { PortBindingHostPort } from './port-binding-host-port';

export interface PortBinding {
  HostIp?: PortBindingHostIp;
  HostPort?: PortBindingHostPort;
}
