/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PortMappingHostPort } from './port-mapping-host-port';
import type { PortMappingContainerPort } from './port-mapping-container-port';

export interface PortMapping {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  hostPort?: PortMappingHostPort;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  containerPort?: PortMappingContainerPort;
}
