/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { RestartPolicyKind } from './restart-policy-kind';
import type { RestartPolicyMaximumRetryCount } from './restart-policy-maximum-retry-count';

export interface RestartPolicy {
  Name?: RestartPolicyKind;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  MaximumRetryCount?: RestartPolicyMaximumRetryCount;
}
