/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export type Status = typeof Status[keyof typeof Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Status = {
  Created: 'Created',
  Exited: 'Exited',
  Dead: 'Dead',
  Paused: 'Paused',
  Restarting: 'Restarting',
  Removing: 'Removing',
  Running: 'Running',
} as const;
