/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ThrottleDevicePath } from './throttle-device-path';
import type { ThrottleDeviceRate } from './throttle-device-rate';

export interface ThrottleDevice {
  Path?: ThrottleDevicePath;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  Rate?: ThrottleDeviceRate;
}
