/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TmpfsOptionsSizeBytes } from './tmpfs-options-size-bytes';
import type { TmpfsOptionsMode } from './tmpfs-options-mode';
import type { TmpfsOptionsOptions } from './tmpfs-options-options';

export interface TmpfsOptions {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  SizeBytes?: TmpfsOptionsSizeBytes;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  Mode?: TmpfsOptionsMode;
  Options?: TmpfsOptionsOptions;
}
