/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UlimitName } from './ulimit-name';
import type { UlimitHard } from './ulimit-hard';
import type { UlimitSoft } from './ulimit-soft';

export interface Ulimit {
  Name?: UlimitName;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  Hard?: UlimitHard;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  Soft?: UlimitSoft;
}
