/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { VolumeOptionsLabelsAnyOf } from './volume-options-labels-any-of';

export type VolumeOptionsLabels = null | VolumeOptionsLabelsAnyOf;
