/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { VolumeOptionsLabels } from './volume-options-labels';
import type { VolumeOptionsSubpath } from './volume-options-subpath';
import type { Driver } from './driver';

export interface VolumeOptions {
  NoCopy?: boolean;
  Labels?: VolumeOptionsLabels;
  Subpath?: VolumeOptionsSubpath;
  DriverConfig?: Driver;
}
