/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { WeightDevicePath } from './weight-device-path';
import type { WeightDeviceWeight } from './weight-device-weight';

export interface WeightDevice {
  Path?: WeightDevicePath;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  Weight?: WeightDeviceWeight;
}
