/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  useQuery
} from 'react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  ComposeDetailModel,
  ComposeListItemModel,
  ProblemDetails
} from '../models';



type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export const getCompose = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ComposeListItemModel[]>> => {
    
    
    return axios.get(
      `/Compose`,options
    );
  }




export const getGetComposeQueryKey = () => {
    return [
    `/Compose`
    ] as const;
    }

    
export const getGetComposeQueryOptions = <TData = Awaited<ReturnType<typeof getCompose>>, TError = AxiosError<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCompose>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetComposeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompose>>> = ({ signal }) => getCompose({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCompose>>, TError, TData> & { queryKey: QueryKey }
}

export type GetComposeQueryResult = NonNullable<Awaited<ReturnType<typeof getCompose>>>
export type GetComposeQueryError = AxiosError<void>



export function useGetCompose<TData = Awaited<ReturnType<typeof getCompose>>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCompose>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetComposeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getComposeIdentifier = (
    identifier: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ComposeDetailModel>> => {
    
    
    return axios.get(
      `/Compose/${identifier}`,options
    );
  }




export const getGetComposeIdentifierQueryKey = (identifier?: string,) => {
    return [
    `/Compose/${identifier}`
    ] as const;
    }

    
export const getGetComposeIdentifierQueryOptions = <TData = Awaited<ReturnType<typeof getComposeIdentifier>>, TError = AxiosError<ProblemDetails>>(identifier: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getComposeIdentifier>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetComposeIdentifierQueryKey(identifier);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getComposeIdentifier>>> = ({ signal }) => getComposeIdentifier(identifier, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(identifier), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getComposeIdentifier>>, TError, TData> & { queryKey: QueryKey }
}

export type GetComposeIdentifierQueryResult = NonNullable<Awaited<ReturnType<typeof getComposeIdentifier>>>
export type GetComposeIdentifierQueryError = AxiosError<ProblemDetails>



export function useGetComposeIdentifier<TData = Awaited<ReturnType<typeof getComposeIdentifier>>, TError = AxiosError<ProblemDetails>>(
 identifier: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getComposeIdentifier>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetComposeIdentifierQueryOptions(identifier,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




