/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.Docker.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  useMutation,
  useQuery
} from 'react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  ContainerDetailModel,
  ContainerListItemModel,
  CreateContainerParameters,
  ProblemDetails
} from '../models';



type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export const getContainer = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ContainerListItemModel[]>> => {
    
    
    return axios.get(
      `/Container`,options
    );
  }




export const getGetContainerQueryKey = () => {
    return [
    `/Container`
    ] as const;
    }

    
export const getGetContainerQueryOptions = <TData = Awaited<ReturnType<typeof getContainer>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getContainer>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContainerQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContainer>>> = ({ signal }) => getContainer({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContainer>>, TError, TData> & { queryKey: QueryKey }
}

export type GetContainerQueryResult = NonNullable<Awaited<ReturnType<typeof getContainer>>>
export type GetContainerQueryError = AxiosError<unknown>



export function useGetContainer<TData = Awaited<ReturnType<typeof getContainer>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getContainer>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetContainerQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putContainer = (
    createContainerParameters: CreateContainerParameters, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.put(
      `/Container`,
      createContainerParameters,{
        responseType: 'text',
    ...options,}
    );
  }



export const getPutContainerMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putContainer>>, TError,{data: CreateContainerParameters}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putContainer>>, TError,{data: CreateContainerParameters}, TContext> => {

const mutationKey = ['putContainer'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putContainer>>, {data: CreateContainerParameters}> = (props) => {
          const {data} = props ?? {};

          return  putContainer(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutContainerMutationResult = NonNullable<Awaited<ReturnType<typeof putContainer>>>
    export type PutContainerMutationBody = CreateContainerParameters
    export type PutContainerMutationError = AxiosError<void>

    export const usePutContainer = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putContainer>>, TError,{data: CreateContainerParameters}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putContainer>>,
        TError,
        {data: CreateContainerParameters},
        TContext
      > => {

      const mutationOptions = getPutContainerMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const getContainerIdentifier = (
    identifier: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ContainerDetailModel>> => {
    
    
    return axios.get(
      `/Container/${identifier}`,options
    );
  }




export const getGetContainerIdentifierQueryKey = (identifier?: string,) => {
    return [
    `/Container/${identifier}`
    ] as const;
    }

    
export const getGetContainerIdentifierQueryOptions = <TData = Awaited<ReturnType<typeof getContainerIdentifier>>, TError = AxiosError<ProblemDetails>>(identifier: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getContainerIdentifier>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContainerIdentifierQueryKey(identifier);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContainerIdentifier>>> = ({ signal }) => getContainerIdentifier(identifier, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(identifier), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContainerIdentifier>>, TError, TData> & { queryKey: QueryKey }
}

export type GetContainerIdentifierQueryResult = NonNullable<Awaited<ReturnType<typeof getContainerIdentifier>>>
export type GetContainerIdentifierQueryError = AxiosError<ProblemDetails>



export function useGetContainerIdentifier<TData = Awaited<ReturnType<typeof getContainerIdentifier>>, TError = AxiosError<ProblemDetails>>(
 identifier: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getContainerIdentifier>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetContainerIdentifierQueryOptions(identifier,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteContainerIdentifier = (
    identifier: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/Container/${identifier}`,options
    );
  }



export const getDeleteContainerIdentifierMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContainerIdentifier>>, TError,{identifier: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteContainerIdentifier>>, TError,{identifier: string}, TContext> => {

const mutationKey = ['deleteContainerIdentifier'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteContainerIdentifier>>, {identifier: string}> = (props) => {
          const {identifier} = props ?? {};

          return  deleteContainerIdentifier(identifier,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteContainerIdentifierMutationResult = NonNullable<Awaited<ReturnType<typeof deleteContainerIdentifier>>>
    
    export type DeleteContainerIdentifierMutationError = AxiosError<unknown>

    export const useDeleteContainerIdentifier = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContainerIdentifier>>, TError,{identifier: string}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteContainerIdentifier>>,
        TError,
        {identifier: string},
        TContext
      > => {

      const mutationOptions = getDeleteContainerIdentifierMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const putContainerIdentifierStart = (
    identifier: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.put(
      `/Container/${identifier}/start`,undefined,options
    );
  }



export const getPutContainerIdentifierStartMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putContainerIdentifierStart>>, TError,{identifier: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putContainerIdentifierStart>>, TError,{identifier: string}, TContext> => {

const mutationKey = ['putContainerIdentifierStart'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putContainerIdentifierStart>>, {identifier: string}> = (props) => {
          const {identifier} = props ?? {};

          return  putContainerIdentifierStart(identifier,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutContainerIdentifierStartMutationResult = NonNullable<Awaited<ReturnType<typeof putContainerIdentifierStart>>>
    
    export type PutContainerIdentifierStartMutationError = AxiosError<void>

    export const usePutContainerIdentifierStart = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putContainerIdentifierStart>>, TError,{identifier: string}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putContainerIdentifierStart>>,
        TError,
        {identifier: string},
        TContext
      > => {

      const mutationOptions = getPutContainerIdentifierStartMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const putContainerIdentifierStop = (
    identifier: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.put(
      `/Container/${identifier}/stop`,undefined,options
    );
  }



export const getPutContainerIdentifierStopMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putContainerIdentifierStop>>, TError,{identifier: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putContainerIdentifierStop>>, TError,{identifier: string}, TContext> => {

const mutationKey = ['putContainerIdentifierStop'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putContainerIdentifierStop>>, {identifier: string}> = (props) => {
          const {identifier} = props ?? {};

          return  putContainerIdentifierStop(identifier,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutContainerIdentifierStopMutationResult = NonNullable<Awaited<ReturnType<typeof putContainerIdentifierStop>>>
    
    export type PutContainerIdentifierStopMutationError = AxiosError<void>

    export const usePutContainerIdentifierStop = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putContainerIdentifierStop>>, TError,{identifier: string}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putContainerIdentifierStop>>,
        TError,
        {identifier: string},
        TContext
      > => {

      const mutationOptions = getPutContainerIdentifierStopMutationOptions(options);

      return useMutation(mutationOptions);
    }
    