worker_processes auto;

events {
    worker_connections  1024;
}

http {
    server {
        listen                      80;
        server_name                 localhost;
        keepalive_timeout           70;

        root                        /usr/share/nginx/html/weaver;
        index                       index.html index.html;
        include                     /etc/nginx/mime.types;

        gzip                        on;
        gzip_min_length             1000;
        gzip_proxied                expired no-cache no-store private auth;
        gzip_types                  text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        error_log                   /dev/stderr debug;

        #TODO: add_header                  Content-Security-Policy "script-src 'self' 'unsafe-inline';style-src 'self' 'unsafe-inline';img-src 'self' data:;font-src 'self';frame-ancestors 'self' https://localhost;block-all-mixed-content;";
        
        location / {
            try_files               $uri $uri/ /index.html;
        }
    }   
}