/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ComposeProjectDetailModelDescription } from './compose-project-detail-model-description';

export interface ComposeProjectDetailModel {
  id?: string;
  name?: string;
  description?: ComposeProjectDetailModelDescription;
  tags?: string[];
}
