/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Tag } from './tag';

export type CreateProjectCommandTags = null | Tag[];
