/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProjectCommandDescription } from './create-project-command-description';
import type { CreateProjectCommandTags } from './create-project-command-tags';

export interface CreateProjectCommand {
  name: string;
  description?: CreateProjectCommandDescription;
  tags?: CreateProjectCommandTags;
}
