/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ProblemDetailsType } from './problem-details-type';
import type { ProblemDetailsTitle } from './problem-details-title';
import type { ProblemDetailsStatus } from './problem-details-status';
import type { ProblemDetailsDetail } from './problem-details-detail';
import type { ProblemDetailsInstance } from './problem-details-instance';

export interface ProblemDetails {
  type?: ProblemDetailsType;
  title?: ProblemDetailsTitle;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  status?: ProblemDetailsStatus;
  detail?: ProblemDetailsDetail;
  instance?: ProblemDetailsInstance;
}
