/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { OptionType } from './option-type';

export type PutServiceOptionParams = {
name?: string;
type?: OptionType;
};
