/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { OptionType2 } from './option-type2';

export type PutServiceOptionParams = {
name?: string;
type?: OptionType2;
};
