/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceOptionModel } from './service-option-model';

export interface ServiceDetailModel {
  id?: string;
  name?: string;
  templateId?: string;
  options?: ServiceOptionModel[];
}
