/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { OptionType } from './option-type';

export interface ServiceOptionModel {
  name?: string;
  type?: OptionType;
  value?: unknown;
  /** @nullable */
  id?: string | null;
}
