/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { OptionType } from './option-type';
import type { ServiceOptionModelId } from './service-option-model-id';

export interface ServiceOptionModel {
  name?: string;
  type?: OptionType;
  value?: unknown;
  id?: ServiceOptionModelId;
}
