/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceTemplateOptionModelId } from './service-template-option-model-id';
import type { OptionType } from './option-type';

export interface ServiceTemplateOptionModel {
  id: ServiceTemplateOptionModelId;
  name: string;
  type: OptionType;
}
