/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceType2 } from './service-type2';

export interface ServiceTemplateListItemModel {
  id?: string;
  name: string;
  type: ServiceType2;
}
