/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ServiceListItemModel {
  id?: string;
  name?: string;
  templateId?: string;
}
