/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceType2 } from './service-type2';
import type { ServiceTemplateOptionModel } from './service-template-option-model';

export interface ServiceTemplateDetailModel {
  id?: string;
  name: string;
  type: ServiceType2;
  config?: ServiceTemplateOptionModel[];
}
