/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Weaver.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TagId } from './tag-id';

export interface Tag {
  name: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: TagId;
  uuid?: string;
}
